export const FETCH_REGIONS = "FETCH_REGIONS";
export const SET_REGIONS = "SET_REGIONS";
export const SET_REGIONS_LOADED = "SET_REGIONS_LOADED";

export const FETCH_CITIES = "FETCH_CITIES";
export const SET_CITIES = "SET_CITIES";
export const SET_CITIES_LOADED = "SET_CITIES_LOADED";

export const FETCH_FEEDBACK = "FETCH_FEEDBACK";
export const SET_FEEDBACK = "SET_FEEDBACK";
export const SET_FEEDBACK_LOADED = "SET_FEEDBACK_LOADED";
export const POST_FEEDBACK = "POST_FEEDBACK";
export const PUT_FEEDBACK = "PUT_FEEDBACK";
export const DELETE_FEEDBACK = "DELETE_FEEDBACK";
