export const FETCH_REGIONS = "FETCH_REGIONS";
export const SET_REGIONS = "SET_REGIONS";
export const SET_REGIONS_LOADED = "SET_REGIONS_LOADED";

export const FETCH_CITYES = "FETCH_CITYES";
export const SET_CITYES = "SET_CITYES";
export const SET_CITYES_LOADED = "SET_CITYES_LOADED";

export const FETCH_FEEDBACK = "FETCH_FEEDBACK";
export const SET_FEEDBACK = "SET_FEEDBACK";
export const SET_FEEDBACK_LOADED = "SET_FEEDBACK_LOADED";
